program
  : code_blocks+ // infinite code_blocks
  ;

code_blocks
  : func_def
  : statement
  ;

statement
  : assignment NEW_LINE
  | return NEW_LINE
  | func_call
  ;

func_def 
  : 'func' label paren_assignment "does" equals "by" statement "end"
  ;

func_call
  : label paren_comma_term
  ; 

paren_assignment
  : '(' assignment ')'
  ;

paren_index
  : '(' index ')'
  ;

paren_comma_term
  : '(' comma_term ')' 
  ;

index
  : label
  | label ',' index
  ;

comma_term
  : term
  | term ',' comma_term
  ;

return 
  : 'return' term
  ;

assignment
  | label '=' term
  ;

equals
  | term "is" term 
  ; 

math
  : term '+' term
  | term '-' term
  ;

term
  : label
  | literal
  | func_call
  | equals
  ;

label
  : STRING
  ;

literal
  : STRING
  | INT 
  ;

STRING
  : [a-zA-Z]+
  ;

INT
  : [0-9]+
  ;

NEW_LINE
  : '\n'
  ;
