// Code generated by "stringer --type=Symbol"; DO NOT EDIT.

package main

import "strconv"

const _Symbol_name = "FUNCLABELCOLONL_PARENR_PARENEND"

var _Symbol_index = [...]uint8{0, 4, 9, 14, 21, 28, 31}

func (i Symbol) String() string {
	if i < 0 || i >= Symbol(len(_Symbol_index)-1) {
		return "Symbol(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Symbol_name[_Symbol_index[i]:_Symbol_index[i+1]]
}
